accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

cars/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cars'
urlpatterns = [
    path('', views.cars, name='cars'),
    path('search/', views.search, name='search'),
    path('<str:slug>/', views.car_detail, name='car-detail'),
]

carsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cars/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

templates/includes/footer.html
<!-- Footer start -->
<footer class="footer">
    
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <p class="copy">© {% now 'Y' %} <a href="#">Carsite Corp.</a> All Rights Reserved.</p>
                </div>
                <div class="col-lg-4">
                    <div class="social-list-2">
                        <ul>
                            <li><a href="https://www.facebook.com/" target="_blank" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://www.twitter.com/" target="_blank" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.instagram.com/" target="_blank" class="instagram-bg"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="https://www.linkedin.com/" target="_blank" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer end -->

templates/includes/messages.html
{% if messages %}

    {% for message in messages %}
    
        <div id="message" class="container">
            <div class="alert alert-{{message.tags}}" alert-dismissable role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{message.tags|title}}
                    {% endif %}
                </strong>
                {{message}}
            </div>
        </div>
    
    {% endfor %}

{% endif %}

templates/includes/navbar.html
{% load static %}

<!-- Main header start -->
<header class="main-header sticky-header header-with-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand company-logo" href="{% url "pages:home" %}">
                <img src="" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a
                            {% if '/' == request.path %}
                            class="nav-link active"
                            {% else %}
                            class="nav-link"
                            {% endif %}
                            href="{% url "pages:home" %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            {% if 'cars' in request.path %}
                            class="nav-link active"
                            {% else %}
                            class="nav-link"
                            {% endif %}
                            href="{% url "cars:cars" %}">
                            Cars
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            {% if 'about' in request.path %}
                            class="nav-link active"
                            {% else %}
                            class="nav-link"
                            {% endif %}
                            href="{% url "pages:about" %}">
                            About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            {% if 'services' in request.path %}
                            class="nav-link active"
                            {% else %}
                            class="nav-link"
                            {% endif %}
                            href="{% url "pages:services" %}">
                            Services
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a
                            {% if 'contact' in request.path %}
                            class="nav-link active"
                            {% else %}
                            class="nav-link"
                            {% endif %} 
                            href="{% url "pages:contact" %}">
                            Contact
                        </a>
                    </li>
                    <li class="nav-item dropdown m-hide">
                        <a href="#full-page-search" class="nav-link h-icon">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!-- Main header end -->

templates/includes/topbar.html
<!-- Top header start -->
<header class="top-header th-2 top-header-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-7">
                <div class="list-inline">
                    <a href="tel:+55-4XX-634-7071"><i class="fa fa-phone"></i>+55-4XX-634-7071</a>
                    <a href="contact@carsite.com"><i class="fa fa-envelope"></i>contact@carsite.com</a>
                    <a href="contact@carsite.com"><i class="fa fa-clock-o"></i>Mon - Sun: 8:00am - 6:00pm</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-5">
                <ul class="top-social-media pull-right">
                    {% if not user.is_authenticated %}
                    <li>
                        <a href="{% url "accounts:login" %}" class="sign-in"><i class="fa fa-sign-in"></i> Login</a>
                    </li>
                    <li>
                        <a href="{% url "accounts:register" %}" class="sign-in"><i class="fa fa-user"></i> Register</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url "accounts:dashboard" %}" class="sign-in"><i class="fa fa-tachometer"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="javascript:{document.getElementById('logout').submit()}" class="sign-in"><i class="fa fa-sign-out"></i> Logout</a>
                        <form action="{% url "accounts:logout" %}" id="logout" method="POST">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- Top header end -->