cars/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cars'
urlpatterns = [
    path('', views.cars, name='cars'),
    path('search/', views.search, name='search'),
    path('<str:slug>/', views.car_detail, name='car-detail'),
]

carsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cars/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

cars/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from multiselectfield import MultiSelectField
from autoslug import AutoSlugField

class Cars(models.Model):
    class Meta:
        verbose_name_plural = 'Cars'
        ordering = ['created_date']

    def __str__(self) -> str:
        return f'{self.car_title} - {self.car_reg_number}'
    
    indian_states = (
    ('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'),
    ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'),
    ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'),
    ('KL', 'Kerala'), ('LD', 'Ladakh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'),
    ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'),
    ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'),
    ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'),
    ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'),
    )

    features_choices = (
        ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'),
        ('Anti-lock Braking System (ABS)', 'Anti-lock Braking System (ABS)'), ('Audio Interface', 'Audio Interface'), ('Auto Start/Stop', 'Auto Start/Stop'),
        ('Bluetooth Handset', 'Bluetooth Handset'), ('Central Locking System', 'Central Locking System'), ('Cruise Control', 'Cruise Control'),
        ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'),
        ('Reversing Camera', 'Reversing Camera'), ('Seat Heating', 'Seat Heating'), ('Wind Deflector', 'Wind Deflector'), ('Alloy Wheels', 'Alloy Wheels'),
    )

    door_choices = (
        (1, '1'), (2, '2'), (3, '3'),
        (4, '4'), (5, '5'), (7, '7'),
        (8, '8'), (9, '9'), (10, '10'),
    )

    transmission_choices = (
        ('Manual', 'Manual'),
        ('Automatic', 'Automatic'),
    )

    fuel_choices = (
        ('Petrol', 'Petrol'),
        ('Diesel', 'Diesel'), 
        ('CNG', 'CNG'),
        ('Electric', 'Electric'),
    )

    drivetrain_choices = (
        ('Front Wheel Drive (FWD)', 'Front Wheel Drive (FWD)'),
        ('Rear Wheel Drive (RWD)', 'Rear Wheel Drive (RWD)'),
        ('All Wheel Drive (AWD)', 'All Wheel Drive (AWD)'),
        ('4 Wheel Drive (4WD)', '4 Wheel Drive (4WD)'),
    )

    condition_choices = (
        ('New', 'New'),
        ('Used', 'Used'),
    )

    year_choice = []
    for y in range(datetime.now().year, 1949, -1):
        year_choice.append((y, y))

    def save(self, *args, **kwargs):
        # If the car_title has changed, update the slug field
        if self.car_title and self.slug != self.car_title:
            self.slug = self.car_title
        super().save(*args, **kwargs)
    
    car_brand = models.CharField(max_length=200)
    car_title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='car_title', unique=True, null=True, default=None)
    state = models.CharField(choices=indian_states, max_length=200)
    city = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    year = models.PositiveIntegerField(('year'), choices=year_choice)
    condition = models.CharField(choices=condition_choices, max_length=200)
    price = models.PositiveIntegerField()
    description = RichTextField()
    car_photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    car_photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    features = MultiSelectField(choices=features_choices, max_length=2000)
    body_style = models.CharField(max_length=200)
    engine = models.CharField(max_length=200)
    drivetrain = models.CharField(choices=drivetrain_choices, max_length=500)
    transmission_type = models.CharField(choices=transmission_choices, max_length=200)
    interior = models.CharField(max_length=200)
    kilometers = models.PositiveIntegerField()
    doors = models.PositiveIntegerField(choices=door_choices)
    passengers = models.PositiveIntegerField()
    car_reg_number = models.CharField(max_length=200)
    mileage = models.PositiveIntegerField()
    fuel_type = models.CharField(choices=fuel_choices, max_length=200)
    no_of_owners = models.PositiveIntegerField()
    is_featured = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=datetime.now, blank=True)

cars/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from .models import Cars

def cars(request):
    cars = Cars.objects.order_by('-is_featured')
    paginator = Paginator(cars, 4)
    page = request.GET.get('page')
    paged_cars = paginator.get_page(page)

    search_car = Cars.objects.order_by('car_title').values_list('car_title', flat=True).distinct()
    search_brand = Cars.objects.order_by('car_brand').values_list('car_brand', flat=True).distinct()
    search_location = Cars.objects.order_by('city').values_list('city', flat=True).distinct()
    search_year = Cars.objects.order_by('-year').values_list('year', flat=True).distinct()
    search_body = Cars.objects.order_by('body_style').values_list('body_style', flat=True).distinct()

    data = {
        'cars': paged_cars,
        'search_car': search_car,
        'search_brand': search_brand,
        'search_location': search_location,
        'search_year': search_year,
        'search_body': search_body,
    }
    return render(request, 'cars/cars.html', data)

def car_detail(request, slug):
    car_detail = get_object_or_404(Cars, slug=slug)
    data = {'car_detail': car_detail}
    return render(request, 'cars/car_detail.html', data)

def search(request):
    cars = Cars.objects.order_by('-is_featured')

    search_brand = Cars.objects.order_by('car_brand').values_list('car_brand', flat=True).distinct()
    search_car = Cars.objects.order_by('car_title').values_list('car_title', flat=True).distinct()
    search_location = Cars.objects.order_by('city').values_list('city', flat=True).distinct()
    search_year = Cars.objects.order_by('-year').values_list('year', flat=True).distinct()
    search_body = Cars.objects.order_by('body_style').values_list('body_style', flat=True).distinct()

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            cars = cars.filter(car_title__icontains=keyword)

    if 'car_title' in request.GET:
        car_title = request.GET['car_title']
        if car_title:
            cars = cars.filter(car_title__iexact=car_title)

    if 'car_brand' in request.GET:
        car_brand = request.GET['car_brand']
        if car_brand:
            cars = cars.filter(car_brand__iexact=car_brand)

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            cars = cars.filter(city__iexact=city)

    if 'year' in request.GET:
        year = request.GET['year']
        if year:
            cars = cars.filter(year__iexact=year)

    if 'body_style' in request.GET:
        body_style = request.GET['body_style']
        if city:
            body_style = cars.filter(body_style__iexact=body_style)

    if 'min_price' in request.GET:
        min_price = request.GET['min_price']
        max_price = request.GET['max_price']
        if max_price:
            cars = cars.filter(price__gte=min_price, price__lte=max_price)

    data = {
        'cars': cars,
        'search_brand': search_brand,
        'search_car': search_car,
        'search_location': search_location,
        'search_year': search_year,
        'search_body': search_body,
    }
    return render(request, 'cars/search.html', data)

templates/cars/cars.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Cars Inventory{% endblock title %}

{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Our Car Inventory</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url "pages:home" %}">Home</a></li>
                <li class="active">Cars</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Featured car start -->
<div class="featured-car content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for car in cars %}
                    <div class="col-lg-6 col-md-6">
                        <div class="car-box-3">
                            <div class="car-thumbnail">
                                <a href="{% url "cars:car-detail" car.slug %}" class="car-img">
                                    {% if car.is_featured %}
                                    <div class="tag-2">Featured</div>
                                    {% endif %}
                                    <div class="price-box">
                                        <span>${{car.price|intcomma}}</span>
                                    </div>
                                    <img class="d-block w-100" src="{{car.car_photo.url}}" alt="car" style="min-height: 262px; max-height: 262px;">
                                </a>
                                <div class="carbox-overlap-wrapper">
                                    <div class="overlap-box">
                                        <div class="overlap-btns-area">
                                            <div class="car-magnify-gallery">
                                                <a href="{{car.car_photo.url}}" class="overlap-btn">
                                                    <i class="fa fa-expand"></i>
                                                    <img class="hidden" src="{{car.car_photo.url}}">
                                                </a>
                                                {% if car.car_photo_1 %}
                                                <a href="{{car.car_photo_1.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_1.url}}">
                                                </a>
                                                {% endif %}
        
                                                {% if car.car_photo_2 %}
                                                <a href="{{car.car_photo_2.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_2.url}}">
                                                </a>
                                                {% endif %}
        
                                                {% if car.car_photo_3 %}
                                                <a href="{{car.car_photo_3.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_3.url}}">
                                                </a>
                                                {% endif %}
        
                                                {% if car.car_photo_4 %}
                                                <a href="{{car.car_photo_4.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_4.url}}">
                                                </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="detail">
                                <h1 class="title">
                                    <a href="{% url "cars:car-detail" car.slug %}">{{car.car_title}}</a>
                                </h1>
                                <div class="location">
                                    <i class="flaticon-pin"></i>{{car.city}}, {{car.state}}
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li>{{car.fuel_type}}</li>
                                    <li>{{car.kilometers|intcomma}} km</li>
                                    <li>{{car.transmission_type}}</li>
                                    <li>{{car.body_style}}</li>
                                    <li>{{car.color}}</li>
                                    <li>{{car.year}}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- Page navigation start -->
                <div class="pagination-box p-box-2 text-center">
                    <nav aria-label="Page navigation example">
                        {% if cars.has_other_pages %}
                            <ul class="pagination">
                                {% if cars.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{cars.previous_page_number}}"><i class="fa fa-angle-left"></i></a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="#" onclick="return false;"><i class="fa fa-angle-left"></i></a>
                                    </li>
                                {% endif %}

                                {% for num in cars.paginator.page_range %}
                                    <li class="page-item">
                                        <a class="page-link {% if cars.number == num %}active{% endif %}" href="?page={{ num }}">
                                            {{ num }}
                                        </a>
                                    </li>
                                {% endfor %}

                                {% if cars.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{cars.next_page_number}}"><i class="fa fa-angle-right"></i></a>
                                </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="#" onclick="return false;"><i class="fa fa-angle-right"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="sidebar-right">
                    <!-- Advanced search start -->
                    <div class="widget advanced-search2">
                        <h3 class="sidebar-title">Search your desire car</h3>
                        <form action="{% url "cars:search" %}" method="GET">
                            <div class="form-group">
                                <input type="text" name="keyword" placeholder="Search by name" class="form-control">
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="car_brand">
                                    <option selected="true" disabled="disabled">Brand</option>
                                    {% for car_brand in search_brand %}
                                    <option value="{{car_brand}}">{{car_brand}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="car_title">
                                    <option selected="true" disabled="disabled">Select Car</option>
                                    {% for car_title in search_car %}
                                    <option value="{{car_title}}">{{car_title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="city">
                                    <option selected="true" disabled="disabled">Location</option>
                                    {% for city in search_location %}
                                    <option value="{{city}}">{{city}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="year">
                                    <option selected="true" disabled="disabled">Year</option>
                                    {% for year in search_year %}
                                    <option value="{{year}}">{{year}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="body_style">
                                    <option selected="true" disabled="disabled">Select Type Of Car</option>
                                    {% for body_style in search_body %}
                                    <option value="{{body_style}}">{{body_style}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="range-slider clearfix">
                                <label>Price</label>
                                <div data-min="0" data-max="750000"  data-min-name="min_price" data-max-name="max_price" data-unit="USD" class="range-slider-ui ui-slider" aria-disabled="false"></div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="form-group mb-0">
                                <button class="search-button btn">Search</button>
                            </div>
                        </form>
                    </div>
                   
                    <!-- Question start -->
                    <div class="widget question widget-3">
                        <h5 class="sidebar-title">Follow us</h5>
                        <div class="social-list clearfix">
                            <ul>
                                <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="instagram-bg"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#" class="rss-bg"><i class="fa fa-rss"></i></a></li>
                                <li><a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featured car end -->

{% endblock content %}

templates/cars/search.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

<!-- Banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Search Results</h1>
            <ul class="breadcrumbs">
                <li><a href="index.html">Home</a></li>
                <li class="active">Search</li>
            </ul>
        </div>
    </div>
</div>
<!-- Banner end -->

<!-- Search box 3 start -->
<div class="search-box-3 sb-7 bg-active">
    <div class="container">
        <div class="search-area-inner">
            <div class="search-contents">
                <form method="GET" action="{% url "cars:search" %}">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <select class="selectpicker search-fields" name="car_brand">
                                    <option selected="true" disabled="disabled">Select Brand</option>
                                    {% for car_brand in search_brand %}
                                    <option value="{{car_brand}}">{{car_brand}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <select class="selectpicker search-fields" name="car_title">
                                    <option disabled="disabled" selected="selected">Select Car</option>
                                    {% for car_title in search_car %}
                                    <option value="{{car_title}}">{{car_title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <select class="selectpicker search-fields" name="city">
                                    <option disabled="disabled" selected="selected">Select Location</option>
                                    {% for city in search_location %}
                                    <option value="{{city}}">{{city}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <select class="selectpicker search-fields" name="year">
                                    <option disabled="disabled" selected="selected">Select Year</option>
                                    {% for year in search_year %}
                                    <option value="{{year}}">{{year}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <div class="range-slider">
                                    <div data-min="0" data-max="750000" data-unit="USD" data-min-name="min_price" data-max-name="max_price" class="range-slider-ui ui-slider" aria-disabled="false"></div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                            <div class="form-group">
                                <button class="btn btn-block button-theme btn-md">
                                    <i class="fa fa-search"></i>Find
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Search box 3 end -->

<!-- Featured car start -->
<div class="featured-car content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title">
            <h1>Here's your <span>Cars</span></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
        <div class="row">
            {% for car in cars %}
            <div class="col-lg-4 col-md-6">
                <div class="car-box">
                    <div class="car-thumbnail">
                        <a href="{% url "cars:car-detail" car.id %}" class="car-img">
                            <div class="tag">For Sale</div>
                            <img class="d-block w-100" src="{{car.car_photo.url}}" alt="car" style="min-height: 262px; max-height: 262px;">
                            <div class="facilities-list clearfix">
                                <ul>
                                    <li>
                                        <span><i class="flaticon-way"></i></span>{{car.kilometers|intcomma}} km
                                    </li>
                                    <li>
                                        <span><i class="flaticon-calendar-1"></i></span>{{car.year}}
                                    </li>
                                    <li>
                                        <span><i class="flaticon-manual-transmission"></i></span>{{car.transmission_type}}
                                    </li>
                                </ul>
                            </div>
                        </a>
                        <div class="carbox-overlap-wrapper">
                            <div class="overlap-box">
                                <div class="overlap-btns-area">
                                    <div class="car-magnify-gallery">
                                        <a href="{{car.car_photo.url}}" class="overlap-btn">
                                            <i class="fa fa-expand"></i>
                                            <img class="hidden" src="{{car.car_photo.url}}">
                                        </a>
                                        {% if car.car_photo_1 %}
                                        <a href="{{car.car_photo_1.url}}" class="hidden">
                                            <img class="hidden" src="{{car.car_photo_1.url}}">
                                        </a>
                                        {% endif %}

                                        {% if car.car_photo_2 %}
                                        <a href="{{car.car_photo_2.url}}" class="hidden">
                                            <img class="hidden" src="{{car.car_photo_2.url}}">
                                        </a>
                                        {% endif %}

                                        {% if car.car_photo_3 %}
                                        <a href="{{car.car_photo_3.url}}" class="hidden">
                                            <img class="hidden" src="{{car.car_photo_3.url}}">
                                        </a>
                                        {% endif %}

                                        {% if car.car_photo_4 %}
                                        <a href="{{car.car_photo_4.url}}" class="hidden">
                                            <img class="hidden" src="{{car.car_photo_4.url}}">
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="detail">
                        <h1 class="title">
                            <a href="{% url "cars:car-detail" car.id %}">{{car.car_title}}</a>
                        </h1>
                        <div class="location">
                            <a href="{% url "cars:state-cars" car.state %}">
                                <i class="flaticon-pin"></i>{{car.city}}, {{car.state}}
                            </a>
                        </div>
                    </div>
                    <div class="footer clearfix">
                        <div class="pull-left ratings days">
                            <p class="cartype">{{car.body_style}}</p>
                        </div>
                        <div class="pull-right">
                            <p class="price">${{car.price|intcomma}}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Featured car end -->

{% endblock content %}

templates/cars/state_cars.html
{% for cars in state_cars %}

<h1>{{cars}}</h1>

{% endfor %}